class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email , :password , :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/i
  
  validates :name,  :presence => true, 
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex},
                    :uniqueness => { :case_sensitive => false}
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40}

end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: users
#
# * id                 :integer         not null
#   name               :string(255)
#   email              :string(255)
#   created_at         :datetime        not null
#   updated_at         :datetime        not null
#   encrypted_password :string(255)
#
#  Indexes:
#   index_users_on_email  email  unique
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
